# Generated by Django 3.0.4 on 2020-03-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dept_name',
            field=models.CharField(default='NULL', max_length=20),
        ),
    ]
