# Generated by Django 3.0.4 on 2020-03-26 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_department_dept_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='admin_id',
            new_name='admin',
        ),
    ]
